In [ ]:
import requests
import pandas as pd
from IPython.display import Image, display

API_KEY = "c89RE3BYLWbNntFVHIm9xgf6u50yNDjego1rkxGa"
url = "https://api.nasa.gov/planetary/apod"

params = {
    "api_key": API_KEY
}

response = requests.get(url, params=params)
print(response.status_code)
data = response.json()

print(data)
data["url"]

if data["media_type"] == "image":
    display(Image(url=data["url"]))
else:
    print("Today's APOD is not an image.")

print("Title:", data["title"])
print("Date:", data["date"])
print(data["explanation"])

200
{'copyright': 'Mark Killion', 'date': '2026-09-07', 'explanation': "The Pelican Nebula is slowly being transformed.  IC 5070 (an official designation) is divided from the larger North America Nebula by a molecular cloud filled with dark dust.  The deep featured picture from Utah, USA incorporates 25 hours of exposure and brings out great details of this filamentary dust. The Pelican Nebula receives much study because it is a particularly active mix of star formation and evolving gas clouds.  The light from young energetic stars is slowly transforming the cold gas to hot gas, with the advancing boundary between the two, known as an ionization front, visible in bright orange on the upper right. Particularly dense tentacles of cold gas remain.  Millions of years from now, the Pelican Nebula, bounded by dark nebula LDN 935, might no longer be known as the Pelican, as the balance and placement of stars and gas will surely leave something that appears completely different.   APOD's main NASA site is moving: From apod.nasa.gov to science.nasa.gov/apod", 'hdurl': 'https://apod.nasa.gov/apod/image/2609/Pelican_Killion_4800.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'The Pelican Nebula in Gas, Dust, and Stars', 'url': 'https://apod.nasa.gov/apod/image/2609/Pelican_Killion_960.jpg'}

Title: The Pelican Nebula in Gas, Dust, and Stars
Date: 2026-09-07
The Pelican Nebula is slowly being transformed.  IC 5070 (an official designation) is divided from the larger North America Nebula by a molecular cloud filled with dark dust.  The deep featured picture from Utah, USA incorporates 25 hours of exposure and brings out great details of this filamentary dust. The Pelican Nebula receives much study because it is a particularly active mix of star formation and evolving gas clouds.  The light from young energetic stars is slowly transforming the cold gas to hot gas, with the advancing boundary between the two, known as an ionization front, visible in bright orange on the upper right. Particularly dense tentacles of cold gas remain.  Millions of years from now, the Pelican Nebula, bounded by dark nebula LDN 935, might no longer be known as the Pelican, as the balance and placement of stars and gas will surely leave something that appears completely different.   APOD's main NASA site is moving: From apod.nasa.gov to science.nasa.gov/apod

In [ ]:
url = "https://api.nasa.gov/neo/rest/v1/feed"

params = {
    "start_date": "2026-09-01",
    "end_date": "2026-09-07",
    "api_key": API_KEY
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)
asteroid_data = response.json()

asteroid_data.keys()

Status code: 200

dict_keys(['links', 'element_count', 'near_earth_objects'])

In [ ]:
asteroid_data["near_earth_objects"].keys()

dict_keys(['2026-09-07', '2026-09-02', '2026-09-01', '2026-09-04', '2026-09-03', '2026-09-06', '2026-09-05'])

In [ ]:
first_date = list(asteroid_data["near_earth_objects"].keys())[0]

asteroid_data["near_earth_objects"][first_date]

[{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3662879?api_key=c89RE3BYLWbNntFVHIm9xgf6u50yNDjego1rkxGa'},
  'id': '3662879',
  'neo_reference_id': '3662879',
  'name': '(2014 DV110)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3662879',
  'absolute_magnitude_h': 24.9,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0278326768,
    'estimated_diameter_max': 0.0622357573},
   'meters': {'estimated_diameter_min': 27.8326768072,
    'estimated_diameter_max': 62.2357573367},
   'miles': {'estimated_diameter_min': 0.0172944182,
    'estimated_diameter_max': 0.0386714948},
   'feet': {'estimated_diameter_min': 91.3145593761,
    'estimated_diameter_max': 204.1855621004}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2026-09-07',
    'close_approach_date_full': '2026-Sep-07 19:06',
    'epoch_date_close_approach': 1788807960000,
    'relative_velocity': {'kilometers_per_second': '14.3750406375',
     'kilometers_per_hour': '51750.1462948733',
     'miles_per_hour': '32155.528401945'},
    'miss_distance': {'astronomical': '0.4169450512',
     'lunar': '162.1916249168',
     'kilometers': '62374091.566560944',
     'miles': '38757463.2920072672'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3838020?api_key=c89RE3BYLWbNntFVHIm9xgf6u50yNDjego1rkxGa'},
  'id': '3838020',
  'neo_reference_id': '3838020',
  'name': '(2019 BT2)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3838020',
  'absolute_magnitude_h': 20.5,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.2111324448,
    'estimated_diameter_max': 0.4721064988},
   'meters': {'estimated_diameter_min': 211.1324447897,
    'estimated_diameter_max': 472.1064988055},
   'miles': {'estimated_diameter_min': 0.1311915784,
    'estimated_diameter_max': 0.2933532873},
   'feet': {'estimated_diameter_min': 692.6917701639,
    'estimated_diameter_max': 1548.9058855411}},
  'is_potentially_hazardous_asteroid': True,
  'close_approach_data': [{'close_approach_date': '2026-09-07',
    'close_approach_date_full': '2026-Sep-07 10:33',
    'epoch_date_close_approach': 1788777180000,
    'relative_velocity': {'kilometers_per_second': '19.7253908044',
     'kilometers_per_hour': '71011.4068959329',
     'miles_per_hour': '44123.7266904201'},
    'miss_distance': {'astronomical': '0.4629301344',
     'lunar': '180.0798222816',
     'kilometers': '69253362.065053728',
     'miles': '43032043.7648403264'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False},
 {'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/3842692?api_key=c89RE3BYLWbNntFVHIm9xgf6u50yNDjego1rkxGa'},
  'id': '3842692',
  'neo_reference_id': '3842692',
  'name': '(2019 LV)',
  'nasa_jpl_url': 'https://ssd.jpl.nasa.gov/tools/sbdb_lookup.html#/?sstr=3842692',
  'absolute_magnitude_h': 24.26,
  'estimated_diameter': {'kilometers': {'estimated_diameter_min': 0.0373727432,
    'estimated_diameter_max': 0.0835679943},
   'meters': {'estimated_diameter_min': 37.3727431914,
    'estimated_diameter_max': 83.5679942816},
   'miles': {'estimated_diameter_min': 0.0232223388,
    'estimated_diameter_max': 0.0519267282},
   'feet': {'estimated_diameter_min': 122.613990772,
    'estimated_diameter_max': 274.1732183587}},
  'is_potentially_hazardous_asteroid': False,
  'close_approach_data': [{'close_approach_date': '2026-09-07',
    'close_approach_date_full': '2026-Sep-07 20:28',
    'epoch_date_close_approach': 1788812880000,
    'relative_velocity': {'kilometers_per_second': '4.3996804337',
     'kilometers_per_hour': '15838.8495612577',
     'miles_per_hour': '9841.6451621048'},
    'miss_distance': {'astronomical': '0.238929717',
     'lunar': '92.943659913',
     'kilometers': '35743376.74290279',
     'miles': '22209904.421086902'},
    'orbiting_body': 'Earth'}],
  'is_sentry_object': False}]

In [ ]:
asteroids = []

In [ ]:
for date, asteroid_list in asteroid_data["near_earth_objects"].items():

    for asteroid in asteroid_list:

        asteroid_id = asteroid["id"]
        asteroid_name = asteroid["name"]
        absolute_magnitude = asteroid["absolute_magnitude_h"]

        min_diameter = asteroid["estimated_diameter"]["kilometers"]["estimated_diameter_min"]

        relative_velocity = asteroid["close_approach_data"][0]["relative_velocity"]["kilometers_per_second"]

        asteroids.append({
            "Asteroid ID": asteroid_id,
            "Asteroid name": asteroid_name,
            "The Minimal estimated diameter in Kilometre": min_diameter,
            "Absolute_magnitude": absolute_magnitude,
            "Relative_velocity(km/s)": relative_velocity
        })

In [ ]:
df = pd.DataFrame(asteroids)

df

,Asteroid ID,Asteroid name,The Minimal estimated diameter in Kilometre,Absolute_magnitude,Relative_velocity(km/s)
0,3662879,(2014 DV110),0.027833,24.90,14.3750406375
1,3838020,(2019 BT2),0.211132,20.50,19.7253908044
2,3842692,(2019 LV),0.037373,24.26,4.3996804337
3,3689273,(2014 SU1),0.027074,24.96,17.0843396071
4,3772976,(2017 FF101),0.041933,24.01,6.9206255242
5,3841509,(2019 HE),0.012149,26.70,8.7360895266
6,3046149,(2000 RE52),0.090898,22.33,17.5150180771
7,3459879,(2001 SL264),0.252671,20.11,1.6789781929
8,3385827,(2007 SV1),0.030518,24.70,18.6801802098
9,3556968,(2011 CT4),0.207279,20.54,22.1703889087
10,3672731,(2014 KO62),0.015295,26.20,3.9560093257
11,3766132,(2016 YP4),0.010582,27.00,7.4781522561
12,3799705,(2018 DM),0.042126,24.00,11.6123147376
13,3827321,(2018 RD2),0.010199,27.08,9.5830420759
14,3842911,(2019 LL6),0.201630,20.60,13.686249321
15,3752409,(2016 HF2),0.016016,26.10,18.3280985752
16,3836756,(2018 XF2),0.014607,26.30,21.6041004665
17,3843480,(2019 PM),0.053034,23.50,13.3247827911
18,2337075,337075 (1998 QC1),0.290105,19.81,23.3113881971
19,3646736,(2013 QF11),0.031956,24.60,17.9155229925
20,3691849,(2014 SF304),0.009216,27.30,20.4551891568
21,3703077,(2014 YT34),0.030518,24.70,6.4489517444
22,3712669,(2015 DM215),0.038420,24.20,14.2047531374
23,3781304,(2017 QB35),0.003669,29.30,8.9099958866
24,3842887,(2019 LL5),0.515887,18.56,18.2275375759
25,2186822,186822 (2004 FE31),0.732074,17.80,11.2928541655
26,2246138,246138 (2007 OG3),0.595052,18.25,4.9032686301
27,3402204,(2008 CE22),0.013949,26.40,14.2031687809
28,3408592,(2008 GA4),0.361872,19.33,24.2423178417
29,3728931,(2015 TH1),0.058151,23.30,8.4817655945
30,3799798,(2018 EY),0.046191,23.80,13.8746238628
31,3836114,(2018 VV4),0.012722,26.60,7.4756097692
32,3330049,(2006 HC2),0.117640,21.77,21.7358727019
33,3797715,(2018 BX),0.004023,29.10,8.0667863536
34,3843735,(2019 QL7),0.012432,26.65,20.9800052864

In [ ]:
df.head()
df.shape
df.columns
df.info()
print(df.columns.tolist())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Asteroid ID                                  35 non-null     object
 1   Asteroid name                                35 non-null     object
 2   The Minimal estimated diameter in Kilometre  35 non-null     float64
 3   Absolute_magnitude                           35 non-null     float64
 4   Relative_velocity(km/s)                      35 non-null     object
dtypes: float64(2), object(3)
memory usage: 1.5+ KB
['Asteroid ID', 'Asteroid name', 'The Minimal estimated diameter in Kilometre', 'Absolute_magnitude', 'Relative_velocity(km/s)']

In [ ]:
df.isnull().sum()

Asteroid ID                                    0
Asteroid name                                  0
The Minimal estimated diameter in Kilometre    0
Absolute_magnitude                             0
Relative_velocity(km/s)                        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
numeric_columns = [
    "The Minimal estimated diameter in Kilometre",
    "Absolute_magnitude",
    "Relative_velocity(km/s)"
]

df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors="coerce")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Asteroid ID                                  35 non-null     object
 1   Asteroid name                                35 non-null     object
 2   The Minimal estimated diameter in Kilometre  35 non-null     float64
 3   Absolute_magnitude                           35 non-null     float64
 4   Relative_velocity(km/s)                      35 non-null     float64
dtypes: float64(3), object(2)
memory usage: 1.5+ KB

In [ ]:
df = df.reset_index(drop=True)
df.head()

,Asteroid ID,Asteroid name,The Minimal estimated diameter in Kilometre,Absolute_magnitude,Relative_velocity(km/s)
0,3662879,(2014 DV110),0.027833,24.90,14.375041
1,3838020,(2019 BT2),0.211132,20.50,19.725391
2,3842692,(2019 LV),0.037373,24.26,4.399680
3,3689273,(2014 SU1),0.027074,24.96,17.084340
4,3772976,(2017 FF101),0.041933,24.01,6.920626

In [ ]:
df

,Asteroid ID,Asteroid name,The Minimal estimated diameter in Kilometre,Absolute_magnitude,Relative_velocity(km/s)
0,3662879,(2014 DV110),0.027833,24.90,14.375041
1,3838020,(2019 BT2),0.211132,20.50,19.725391
2,3842692,(2019 LV),0.037373,24.26,4.399680
3,3689273,(2014 SU1),0.027074,24.96,17.084340
4,3772976,(2017 FF101),0.041933,24.01,6.920626
5,3841509,(2019 HE),0.012149,26.70,8.736090
6,3046149,(2000 RE52),0.090898,22.33,17.515018
7,3459879,(2001 SL264),0.252671,20.11,1.678978
8,3385827,(2007 SV1),0.030518,24.70,18.680180
9,3556968,(2011 CT4),0.207279,20.54,22.170389
10,3672731,(2014 KO62),0.015295,26.20,3.956009
11,3766132,(2016 YP4),0.010582,27.00,7.478152
12,3799705,(2018 DM),0.042126,24.00,11.612315
13,3827321,(2018 RD2),0.010199,27.08,9.583042
14,3842911,(2019 LL6),0.201630,20.60,13.686249
15,3752409,(2016 HF2),0.016016,26.10,18.328099
16,3836756,(2018 XF2),0.014607,26.30,21.604100
17,3843480,(2019 PM),0.053034,23.50,13.324783
18,2337075,337075 (1998 QC1),0.290105,19.81,23.311388
19,3646736,(2013 QF11),0.031956,24.60,17.915523
20,3691849,(2014 SF304),0.009216,27.30,20.455189
21,3703077,(2014 YT34),0.030518,24.70,6.448952
22,3712669,(2015 DM215),0.038420,24.20,14.204753
23,3781304,(2017 QB35),0.003669,29.30,8.909996
24,3842887,(2019 LL5),0.515887,18.56,18.227538
25,2186822,186822 (2004 FE31),0.732074,17.80,11.292854
26,2246138,246138 (2007 OG3),0.595052,18.25,4.903269
27,3402204,(2008 CE22),0.013949,26.40,14.203169
28,3408592,(2008 GA4),0.361872,19.33,24.242318
29,3728931,(2015 TH1),0.058151,23.30,8.481766
30,3799798,(2018 EY),0.046191,23.80,13.874624
31,3836114,(2018 VV4),0.012722,26.60,7.475610
32,3330049,(2006 HC2),0.117640,21.77,21.735873
33,3797715,(2018 BX),0.004023,29.10,8.066786
34,3843735,(2019 QL7),0.012432,26.65,20.980005

In [ ]:
df.head(10)

,Asteroid ID,Asteroid name,The Minimal estimated diameter in Kilometre,Absolute_magnitude,Relative_velocity(km/s)
0,3662879,(2014 DV110),0.027833,24.90,14.375041
1,3838020,(2019 BT2),0.211132,20.50,19.725391
2,3842692,(2019 LV),0.037373,24.26,4.399680
3,3689273,(2014 SU1),0.027074,24.96,17.084340
4,3772976,(2017 FF101),0.041933,24.01,6.920626
5,3841509,(2019 HE),0.012149,26.70,8.736090
6,3046149,(2000 RE52),0.090898,22.33,17.515018
7,3459879,(2001 SL264),0.252671,20.11,1.678978
8,3385827,(2007 SV1),0.030518,24.70,18.680180
9,3556968,(2011 CT4),0.207279,20.54,22.170389

In [ ]:
df.to_csv("nasa_asteroids.csv", index=False)

In [ ]:
df_csv = pd.read_csv("nasa_asteroids.csv")

df_csv.head()

,Asteroid ID,Asteroid name,The Minimal estimated diameter in Kilometre,Absolute_magnitude,Relative_velocity(km/s)
0,3662879,(2014 DV110),0.027833,24.90,14.375041
1,3838020,(2019 BT2),0.211132,20.50,19.725391
2,3842692,(2019 LV),0.037373,24.26,4.399680
3,3689273,(2014 SU1),0.027074,24.96,17.084340
4,3772976,(2017 FF101),0.041933,24.01,6.920626

In [ ]:
df_csv.shape

(35, 5)

In [ ]:
from google.colab import files

files.download("nasa_asteroids.csv")